/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ops Page */
        get: operations["ops_page_ops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Services */
        get: operations["services_api_ops_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/uptime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Uptime
         * @description Dashboard start timestamp + computed uptime seconds for the topbar.
         */
        get: operations["uptime_api_ops_uptime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Training */
        get: operations["training_api_ops_training_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/training_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Training Health */
        get: operations["training_health_api_ops_training_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/regime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Regime */
        get: operations["regime_api_ops_regime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/sentiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sentiment */
        get: operations["sentiment_api_ops_sentiment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mcp */
        get: operations["mcp_api_ops_mcp_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/trades_risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trades Risk
         * @description Postgres-derived risk numbers + open positions from trade_journal.
         *
         *     Post-2026-05-14: freqtrade /api/v1/status is gone; quanta-core writes
         *     every paper-fill into trade_journal, so open positions come from
         *     ops_db.open_positions() (used by _quanta_open_positions in app.py).
         */
        get: operations["trades_risk_api_ops_trades_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause
         * @description Pause V4 trading. Post-cutover: writes to quanta_schema.run_state
         *     instead of POSTing to dead freqtrade. The V4 runner reads run_state
         *     on every cycle; new BUY proposals are skipped while paused. Existing
         *     positions stay open (use the kill switch to flatten).
         */
        post: operations["pause_api_ops_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/sparklines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sparklines
         * @description Per-pair compact close-price arrays + 24h % change.
         *
         *     Used by the Ops trades panel to render small inline price sparklines.
         *     Default `limit=288` gives true 24h coverage at 5m (288 = 24 × 12);
         *     bump cap to 500 so 1h timeframe (24h = 24 candles) and 1m (24h = 1440)
         *     can be requested explicitly. Coinbase REST fallback covers up to 300
         *     candles per public call.
         */
        get: operations["sparklines_api_ops_sparklines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/regime_config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Regime Config Get
         * @description Return the current regime_gating block + the schema (ranges) for the UI.
         */
        get: operations["regime_config_get_api_ops_regime_config_get"];
        put?: never;
        /**
         * Regime Config Post
         * @description Validate + atomically write the new regime_gating block.
         *
         *     Body must be ``{"regime_gating": {...}}`` matching the existing shape.
         *     We:
         *       1. Accept only known keys; reject extras.
         *       2. Validate each value against its sanity range.
         *       3. Snapshot the old config to ``user_data/data/config-backup-<ts>.json``.
         *       4. Atomic-write the new config (tmp + rename).
         *       5. Quanta-core / unified_risk re-reads on its next cycle (no reload call needed).
         *
         *     Returns the diff in the envelope so the frontend can confirm.
         */
        post: operations["regime_config_post_api_ops_regime_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/risk_gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Risk Gates Get
         * @description Return the current risk_gates block + the schema (ranges) for the UI.
         */
        get: operations["risk_gates_get_api_ops_risk_gates_get"];
        put?: never;
        /**
         * Risk Gates Post
         * @description Validate + atomically write the new risk_gates block.
         *
         *     Body must be ``{"risk_gates": {...}}`` matching the existing shape.
         *     We:
         *       1. Accept only known keys; reject extras.
         *       2. Validate each value against its sanity range.
         *       3. Snapshot the old config to ``user_data/data/config-backup-<ts>.json``.
         *       4. Atomic-write the new config (tmp + rename) — rolls back to the
         *          snapshot if validation throws after the snapshot is taken.
         *       5. Quanta-core / unified_risk re-reads on its next cycle (no reload call needed).
         *
         *     Returns the diff in the envelope so the frontend can confirm.
         */
        post: operations["risk_gates_post_api_ops_risk_gates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_ops_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config Overview
         * @description Live config + env-var presence map. Sensitive values are redacted.
         */
        get: operations["config_overview_api_ops_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_ops_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/rebalance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rebalance Dryrun
         * @description Dry-run: compute proposed new pair_weights but don't write.
         */
        get: operations["rebalance_dryrun_api_ops_rebalance_get"];
        put?: never;
        /** Rebalance Apply */
        post: operations["rebalance_apply_api_ops_rebalance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mcp Tools */
        get: operations["mcp_tools_api_ops_tools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/mcp/{tool_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mcp Call */
        post: operations["mcp_call_api_ops_mcp__tool_name__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/explainability/{base}/{quote}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explainability
         * @description Decision records for the most recent candle ticks.
         *
         *     Two sources joined into one timeline:
         *       - trade_journal rows (full context: TFT/DRL/sentiment/regime + reasoning)
         *       - parsed lines from freqtrade.log of the form
         *         ``[strategy] risk-blocked PAIR: REASON (constraint=NAME)``
         *         for entries the risk governor refused.
         */
        get: operations["explainability_api_ops_explainability__base___quote__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/timeline/{base}/{quote}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timeline */
        get: operations["timeline_api_ops_timeline__base___quote__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/slack_preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Slack Preview
         * @description Live render of today's daily P&L (the same payload the cron will Slack
         *     at 00:00 UTC). Frontend renders this in a Slack-styled card.
         */
        get: operations["slack_preview_api_ops_slack_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/wheel_config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wheel Config
         * @description Active wheel risk-cap config + days-since-applied + Config-B
         *     eligibility timer. Reads stocks/wheel/state/risk_config.json which
         *     is auto-updated by wheel.config_tracker on every wheel cron fire.
         *
         *     Surfaces the "Config A is N days old, Config B promotion eligible in
         *     M days" insight on the dashboard so the operator never again has
         *     silently-stale risk caps (the $50k-pilot anti-pattern that triggered
         *     audit/2026-05-15-wheel-sizing-research.md).
         */
        get: operations["wheel_config_api_ops_wheel_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/stocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stocks Status
         * @description Unified shark + wheel + Alpaca state for the /ops Stocks card.
         *
         *     Reads only from disk (stocks/ is bind-mounted read-only). Live Alpaca
         *     data comes from `wheel/state/account_snapshot.json`, which the
         *     `python -m wheel.cli snapshot` cron writes every few minutes — `age_seconds`
         *     surfaces freshness so a stale snapshot is visible in the UI.
         */
        get: operations["stocks_status_api_ops_stocks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/stock_candles/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stock Candles
         * @description Serve OHLC candles for a stock from the cron-fed JSON cache.
         *
         *     The dashboard never calls Alpaca directly. The `wheel_candles` Hermes
         *     cron writes `stocks/wheel/state/candles_{SYM}_{tf}.json` every 5 min
         *     during market hours; this endpoint streams the cached file as a
         *     Lightweight-Charts-compatible payload.
         */
        get: operations["stock_candles_api_ops_stock_candles__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/stocks_sparklines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stocks Sparklines
         * @description Per-symbol close-price arrays + %-change since first bar in window.
         *
         *     Mirrors the crypto `/sparklines` envelope so the SPA can render the
         *     same PairTelemetry card pattern for the stocks basket.
         *
         *     `timeframe` accepts Alpaca codes: `1Min`, `5Min`, `15Min`, `1Hour`,
         *     `1Day`. `limit=78` × 5Min ≈ 6.5h ≈ one US trading session.
         *
         *     Returns `_envelope(status, data={symbols, timeframe, limit, basket,
         *     market_open})`. Each per-symbol payload carries `{closes, current,
         *     pct_session, bars_count, session_window_h}` or, on failure,
         *     `{closes: [], current: None, pct_session: None, error}`.
         *
         *     GET, no `require_mcp_key` — matches the crypto `/sparklines` pattern.
         *     Read-only operator data.
         */
        get: operations["stocks_sparklines_api_ops_stocks_sparklines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gates
         * @description Per-pair entry-gate matrix: which gate is blocking each pair right now.
         *
         *     Walks every pair in DASHBOARD_PAIRS, pulls the latest row from
         *     freqtrade's pair_candles, and evaluates each entry gate the strategy
         *     enforces in populate_entry_trend(). Returns a grid the dashboard
         *     renders so the operator can see exactly *why* a pair isn't trading.
         *
         *     Gates evaluated (in strategy order):
         *       1. capital_allocation     pair weight > 0
         *       2. do_predict             FreqAI has live predictions
         *       3. volume                 last bar has volume > 0
         *       4. regime                 != trending_down (hard block)
         *       5. up_prob_threshold      up >= base + regime delta
         *       6. tft_confidence         >= TFT_MIN_CONFIDENCE (0.40)
         *       7. high_vol_confidence    not (regime=high_vol AND up < HIGH_VOL_MIN)
         *       8. meta_signal_up         == +1 when DRL active
         *       9. meta_confidence        >= META_MIN_CONFIDENCE (0.40) when DRL active
         *      10. account_capacity       open_count < max_open AND breaker clear
         */
        get: operations["gates_api_ops_gates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/market_hours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Market Hours
         * @description NYSE / US-equities session state for the dashboard.
         *
         *     Hours match the canonical NYSE specification:
         *       Pre-Opening Session: 06:30-09:30 ET   (broker extended typically starts at 04:00)
         *       Core Trading:        09:30-16:00 ET
         *       After-Hours:         16:00-20:00 ET
         *       Closed:              all other times + weekends + holidays
         *
         *     Returns:
         *         is_open:           bool   (core 09:30-16:00 ET weekday, not holiday)
         *         is_extended:       bool   (pre-market OR after-hours; kept for back-compat)
         *         is_pre_market:     bool   (06:30-09:30 ET — NYSE official pre-opening)
         *         is_after_hours:    bool   (16:00-20:00 ET — NYSE official late-session)
         *         is_broker_pre:     bool   (04:00-06:30 ET — Alpaca/IBKR ext window only)
         *         session:           "regular" | "pre_market" | "after_hours" | "broker_pre" | "closed"
         *         last_close_utc:    ISO    (UTC)
         *         next_open_utc:     ISO    (UTC) — next 09:30 ET that isn't a holiday/weekend
         *         next_close_utc:    ISO    (UTC)
         *         now_et:            string in ET for display
         *         weekday:           "Mon" .. "Sun"
         *         holiday_note:      string if today/upcoming is a holiday or early-close; else None
         *
         *     Crypto charts run 24/7 regardless of this payload.
         */
        get: operations["market_hours_api_ops_market_hours_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/flash_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flash Status
         * @description Compact ticker payload for the FlashNewsStripLive card.
         *
         *     Pulls (in parallel where possible) from quanta_schema (V4 open positions
         *     + last fill), public.trade_journal (today's closed P&L count), regime_log
         *     (current regime). Cheap — typical response < 200 bytes.
         */
        get: operations["flash_status_api_ops_flash_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/live_trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live Trades
         * @description Aggregate every active position across crypto + wheel + shark for
         *     the top hero strip. Post-cutover (LIVE_ENGINE_MODE set) reads crypto
         *     from quanta_schema; otherwise legacy freqtrade probe.
         */
        get: operations["live_trades_api_ops_live_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/ollama_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ollama Health
         * @description Latest Ollama health probe — read from /tmp/ollama-health.json that
         *     the cron-driven `python -m user_data.modules.ollama_health` writes.
         */
        get: operations["ollama_health_api_ops_ollama_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/circuit_breakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Circuit Breakers
         * @description Status of all LLM circuit breakers (Ollama + Anthropic, fast + deep).
         *
         *     The shark process owns the breaker registry; the dashboard reads disk
         *     state via discover_from_disk() so it doesn't need to share memory.
         */
        get: operations["circuit_breakers_api_ops_circuit_breakers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/llm_stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Stats
         * @description LLM inference monitor — latency, model routing, counterfactual cost.
         *
         *     Reads two sources:
         *       1. stocks/memory/llm-calls.jsonl  (shark agents, written by
         *          shark.llm.tracker on every chat_json call)
         *       2. sentiment_log table             (crypto sentiment engine, latency
         *          derived from prompt_eval + eval counts that the engine logs)
         *
         *     Returns a single envelope so one card on /ops can render everything.
         */
        get: operations["llm_stats_api_ops_llm_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/combined_portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Combined Portfolio
         * @description Combined crypto + stocks portfolio + drawdown, for the unified card.
         */
        get: operations["combined_portfolio_api_ops_combined_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/shark_briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Shark Briefing
         * @description Parsed Shark daily handoff — today's regime, macro, candidates.
         *
         *     Source of truth: `stocks/memory/DAILY-HANDOFF.md`, written by every Shark
         *     phase. Format (per phase block):
         *         ## pre-market | 09:14 EDT
         *         confirmed: NVDA
         *         skipped: GOOGL, AMD, CCJ, CRDO, XOM
         *         market: bullish=9 bearish=1 of 30
         *         regime: BEAR_VOLATILE
         *         macro: ELEVATED
         *         lessons: none
         *
         *     This is what's behind "why no stocks trades fired today" — the operator
         *     couldn't see Shark's decision flow on the dashboard until now.
         */
        get: operations["shark_briefing_api_ops_shark_briefing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/stocks_ml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stocks Ml
         * @description Stocks ML pipeline status — TFT model freshness, val_acc, generation log.
         *
         *     ALPHA. Reads:
         *       stocks/kb/models/tft/stock_tft_v1_summary.json   (training summary)
         *       stocks/kb/models/evolution_log.json              (EPT generation history)
         *       stocks/memory/cron-stocks-ml-train.log           (last few lines)
         */
        get: operations["stocks_ml_api_ops_stocks_ml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/stock_regime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stock Regime
         * @description SPY-driven simple regime classifier for the dashboard.
         *
         *     Reads cached SPY 1Day bars (cron-fed every 5min during market hours),
         *     computes 50-day MA, 200-day MA, and 5-day return, then classifies into
         *     one of {trending_up, trending_down, mean_reverting, high_volatility}.
         *
         *     No training required — pure rule-based, refreshes whenever the
         *     `wheel_candles` cron runs. Pairs visually with the BTC HMM regime card
         *     so the operator sees both markets at a glance.
         */
        get: operations["stock_regime_api_ops_stock_regime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/shark_override_health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Shark Override Health
         * @description Surface the latest shark BEAR_VOLATILE paper-mode override verification.
         *
         *     Returns the raw payload from override_verify.json plus envelope status:
         *       - status="ok"       when verifier reports healthy
         *       - status="degraded" when verifier reports degraded OR file > 36h old
         *       - status="down"     when verifier reports stalled (>=3 consecutive
         *                           BEAR-regime runs with candidates but no trade) OR
         *                           the file is missing.
         */
        get: operations["shark_override_health_api_ops_shark_override_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/backtest_gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtest Gates
         * @description Latest gates_report per strategy + a promotion_eligible boolean.
         *
         *     Walks ``BACKTEST_RESULTS_DIR`` for files matching
         *     ``gates_report_<strategy>_latest.json`` (written by the weekly Hermes
         *     cron). Each file is parsed and returned as a row in ``data.strategies``;
         *     cards on /ops_spa render one badge strip per row.
         *
         *     The cron writes both a timestamped report and a stable *_latest.json
         *     pointer; we only read the pointer here so the endpoint never sees a
         *     partially-written file (the cron uses copy-then-rename atomicity).
         *
         *     Stale = report older than 8 days (cron runs Sundays; 8d gives 1 missed
         *     week of grace before we surface the strategy as "stale").
         */
        get: operations["backtest_gates_api_ops_backtest_gates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/weekly_training": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Weekly Training
         * @description Weekly LoRA training pipeline status — one row per ModelForge track.
         *
         *     Read-only, no auth dep. Degrades soft: if model-forge is unreachable
         *     we still return the 6-track skeleton + the local reflection count so
         *     the operator card has something useful to show during the build-up
         *     week before the training pipeline goes live.
         *
         *     Envelope contract (see docs/WEEKLY_TRAINING_CARD.md for full schema):
         *
         *         {
         *             "status": "ok" | "degraded",
         *             "data": {
         *                 "tracks": [
         *                     {
         *                         "track_id": "trading-reflector",
         *                         "role": "Reflector",
         *                         "headline_metric": "predictive_hit_rate_30d",
         *                         "current_adapter": "run-XXX__gen3" | None,
         *                         "current_adapter_version": "v20260512" | None,
         *                         "last_train_ts": "2026-05-12T07:30:00+00:00" | None,
         *                         "last_eval_scores": {"faithfulness_regex": 0.81, ...},
         *                         "headline_score": 0.62 | None,
         *                         "eligibility": "promoted" | "shadow" | "regressed" | "no-data",
         *                         "examples_trained_this_week": 47,
         *                     }, ... 6 total
         *                 ],
         *                 "summary": {
         *                     "n_tracks_registered": 6,
         *                     "n_tracks_trained": 4,
         *                     "n_promoted_this_week": 2,
         *                 },
         *                 "reflections_this_week": 12,
         *                 "lessons_injected": 41 | None,
         *                 "next_training_ts": "2026-05-18T06:00:00+00:00",
         *                 "model_forge_url": "http://localhost:8000",
         *                 "model_forge_reachable": True | False,
         *                 "model_forge_error": null | "model-forge unreachable: …",
         *                 "week_started": "2026-05-12T00:00:00+00:00",
         *             },
         *             "error": null | "human-readable summary",
         *             "checked_at": ISO-8601 UTC,
         *         }
         */
        get: operations["weekly_training_api_ops_weekly_training_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/llm_calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Calls
         * @description LLM activity feed — paginated list of recent LLM calls.
         *
         *     Query parameters
         *     ----------------
         *     limit         : int, default 50, max 500
         *     agent         : substring filter (case-insensitive) on the ``agent`` field
         *     model         : substring filter on the ``model`` field
         *     since         : ISO timestamp; only calls newer than this are returned
         *     q             : regex filter; matches against agent + model + tier + role.
         *                     If ``include_text=1`` is also set, the regex is ALSO
         *                     applied to prompt + system_message + response_text.
         *     include_text  : 0 (default) → strip prompt/system/response from the
         *                     response (tiny payload). 1 → keep them.
         *     min_latency   : seconds; reject calls faster than this
         *     max_latency   : seconds; reject calls slower than this
         *     role          : canonical AgentFlow role (regime_tagger, bull_debater,
         *                     bear_debater, arbiter, reflector, indicator_selector).
         *                     Filters records whose raw agent name maps to that
         *                     canonical role via ``_canonical_role()``. Used by the
         *                     Tier-E AgentLogsDrawer to fetch the last N calls for
         *                     one specific pipeline stage with FULL prompt/response.
         *
         *     Response: ``{status, data, error, checked_at}`` where ``data`` is::
         *
         *         {
         *           "calls": [<record>, ...],          # newest first
         *           "total_in_window": <int>,          # before pagination
         *           "summary": {...},                  # 24h-window aggregates
         *           "log_path": "...",                 # for the empty-state hint
         *           "log_size_bytes": <int>,
         *         }
         */
        get: operations["llm_calls_api_ops_llm_calls_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ops/llm_calls/{call_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Llm Call Detail
         * @description Single-record drill-down for the modal.
         *
         *     ``call_id`` is the URL-encoded ISO timestamp (the tracker doesn't
         *     generate UUIDs; timestamps have microsecond resolution so collisions
         *     are practically impossible).
         *
         *     Status codes:
         *       200 — record found in the live file (full payload)
         *       404 — record not found anywhere (live + archives both miss it)
         *       410 — record is in an archive (file rotated); returns the archive
         *             path in ``data.archive_path`` so operator can grep manually
         */
        get: operations["llm_call_detail_api_ops_llm_calls__call_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v4/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * V4 Positions
         * @description Net positions per symbol from the V4 paper ledger.
         *
         *     Aggregates fills: net_qty = SUM(BUY qty) - SUM(SELL qty), avg buy price
         *     weighted by qty. Empty list when no fills exist (which is the
         *     expected state until regime flips and V4 places its first BUYs).
         */
        get: operations["v4_positions_api_v4_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v4/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * V4 Trades
         * @description Recent paper fills joined with their proposals (V4 trade tape).
         */
        get: operations["v4_trades_api_v4_trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v4/debate/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debate History
         * @description Recent V4 decisions.
         *
         *     Reads, in order of preference:
         *       1. `quanta_schema.decisions` postgres table (V4 shadow runner output)
         *       2. `_DEBATE_BUFFER` in-memory ring (future debate orchestrator)
         *       3. Deterministic mock (early bring-up only)
         *
         *     Real-data branch wins as soon as the shadow runner writes a row.
         */
        get: operations["debate_history_api_v4_debate_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v4/debate/stream/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debate Stream
         * @description Server-Sent Events stream of debate events.
         *
         *     Real implementation will subscribe to `quanta_core.agents.debate.events`;
         *     this stub deterministically generates a complete 30s deliberation given
         *     the session id (so reloads replay the same debate, useful for testing).
         */
        get: operations["debate_stream_api_v4_debate_stream__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v4/montecarlo/{trade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Montecarlo
         * @description Monte Carlo path envelope for a given trade id.
         *
         *     Looks up `trade_id` in `_MONTECARLO_BUFFER` (live runs published by
         *     `quanta_core.risk.monte_carlo`); falls back to a deterministic
         *     closed-form normal envelope when no real run is recorded.
         */
        get: operations["montecarlo_api_v4_montecarlo__trade_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v4/adapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Adapters
         * @description Recent LoRA promotions across the 6 debate roles.
         */
        get: operations["adapters_api_v4_adapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v4/adapters/{adapter_id}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adapter Rollback
         * @description Rolls back an adapter to the previous Pareto-frontier champion.
         *
         *     Real impl calls mf-api at `:8000/api/adapters/{id}/rollback`. Here we
         *     only validate the id shape so the UI can wire the round-trip end-to-end.
         */
        post: operations["adapter_rollback_api_v4_adapters__adapter_id__rollback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v4/weekly/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekly Preview */
        get: operations["weekly_preview_api_v4_weekly_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v4/parity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Parity
         * @description Backtest-vs-live parity rows + weekly divergence summary.
         *
         *     Reads from `_PARITY_BUFFER` (live shadow-mode parity oracle output)
         *     when populated, falls back to a deterministic mock otherwise. Weekly
         *     summary stays mocked until the shadow-mode runner has 4+ weeks of
         *     data — that's an explicit Track-D follow-up.
         */
        get: operations["parity_api_v4_parity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v4/screening": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Screening */
        get: operations["screening_api_v4_screening_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index */
        get: operations["index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Docs Page */
        get: operations["docs_page_docs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Pairs */
        get: operations["api_pairs_api_pairs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/universe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Universe
         * @description Single source of truth for all symbols the bot tracks.
         *
         *     Reads user_data/universe.json. Frontend SPAs hit this on mount so
         *     the hero strip + dropdowns reflect whatever's currently configured
         *     without hardcoded fallback lists drifting out of sync.
         *
         *     Path resolution: tries USER_DATA_ROOT env first (default
         *     /app/user_data inside the container, mounted from host's
         *     user_data/), then falls back to repo-relative for host-side dev.
         */
        get: operations["api_universe_api_universe_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Mode
         * @description Active trading engine + mode for the topbar badge.
         *
         *     Post-2026-05-14 (freqtrade decommissioned):
         *       1. If LIVE_ENGINE_MODE env is "live" or "shadow" → V4 (quanta_core)
         *          is the active engine. Mode is "paper" (paper-fill simulator) or
         *          "shadow" (no orders). State is "running" when there's a recent
         *          decision row in quanta_schema.decisions.
         *       2. Otherwise mode=unknown (no fallback engine to probe).
         */
        get: operations["api_mode_api_mode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candles/{base}/{quote}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Candles */
        get: operations["api_candles_api_candles__base___quote__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trades/{base}/{quote}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Trades */
        get: operations["api_trades_api_trades__base___quote__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api State */
        get: operations["api_state_api_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ops_page_ops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    services_api_ops_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    uptime_api_ops_uptime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    training_api_ops_training_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    training_health_api_ops_training_health_get: {
        parameters: {
            query?: {
                identifier?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regime_api_ops_regime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sentiment_api_ops_sentiment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    mcp_api_ops_mcp_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trades_risk_api_ops_trades_risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    pause_api_ops_pause_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sparklines_api_ops_sparklines_get: {
        parameters: {
            query?: {
                timeframe?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regime_config_get_api_ops_regime_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    regime_config_post_api_ops_regime_config_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_gates_get_api_ops_risk_gates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    risk_gates_post_api_ops_risk_gates_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_ops_resume_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_overview_api_ops_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readiness_api_ops_readiness_get: {
        parameters: {
            query?: {
                fast_track?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebalance_dryrun_api_ops_rebalance_get: {
        parameters: {
            query?: {
                window?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rebalance_apply_api_ops_rebalance_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mcp_tools_api_ops_tools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    mcp_call_api_ops_mcp__tool_name__post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                tool_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explainability_api_ops_explainability__base___quote__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                base: string;
                quote: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_ops_timeline__base___quote__get: {
        parameters: {
            query?: {
                hours?: number;
                timeframe?: string;
            };
            header?: never;
            path: {
                base: string;
                quote: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    slack_preview_api_ops_slack_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    wheel_config_api_ops_wheel_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stocks_status_api_ops_stocks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stock_candles_api_ops_stock_candles__symbol__get: {
        parameters: {
            query?: {
                timeframe?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stocks_sparklines_api_ops_stocks_sparklines_get: {
        parameters: {
            query?: {
                timeframe?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gates_api_ops_gates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    market_hours_api_ops_market_hours_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    flash_status_api_ops_flash_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    live_trades_api_ops_live_trades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ollama_health_api_ops_ollama_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    circuit_breakers_api_ops_circuit_breakers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    llm_stats_api_ops_llm_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    combined_portfolio_api_ops_combined_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    shark_briefing_api_ops_shark_briefing_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stocks_ml_api_ops_stocks_ml_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    stock_regime_api_ops_stock_regime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    shark_override_health_api_ops_shark_override_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    backtest_gates_api_ops_backtest_gates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    weekly_training_api_ops_weekly_training_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    llm_calls_api_ops_llm_calls_get: {
        parameters: {
            query?: {
                limit?: number;
                agent?: string | null;
                since?: string | null;
                q?: string | null;
                include_text?: number;
                model?: string | null;
                min_latency?: number | null;
                max_latency?: number | null;
                role?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    llm_call_detail_api_ops_llm_calls__call_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                call_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v4_positions_api_v4_positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    v4_trades_api_v4_trades_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debate_history_api_v4_debate_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    debate_stream_api_v4_debate_stream__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    montecarlo_api_v4_montecarlo__trade_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trade_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    adapters_api_v4_adapters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    adapter_rollback_api_v4_adapters__adapter_id__rollback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                adapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    weekly_preview_api_v4_weekly_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    parity_api_v4_parity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    screening_api_v4_screening_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    index__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    docs_page_docs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    api_pairs_api_pairs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_universe_api_universe_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_mode_api_mode_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_candles_api_candles__base___quote__get: {
        parameters: {
            query?: {
                timeframe?: string;
                limit?: number;
            };
            header?: never;
            path: {
                base: string;
                quote: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_trades_api_trades__base___quote__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                base: string;
                quote: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_state_api_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
