-- schema.sql — fully composed quanta_core ledger schema.
--
-- This file is the union of every migration under ``migrations/`` and is
-- regenerated by hand whenever a new migration is added. It is intended for
-- inspection ("what does the schema look like today?") and for the one-shot
-- bootstrap helper in ``PostgresLedger.apply_schema_sql``.
--
-- Production deployments should prefer the versioned migration runner
-- (``PostgresLedger.migrate``) — this file does NOT track which versions
-- have already been applied.
--
-- Tables:
--   * quanta_schema_version — migration log
--   * reservations          — UNIQUE-constrained idempotency reserve slots
--   * proposals             — every order intent, keyed by client_order_id
--   * orders                — exchange acknowledgement state per proposal
--   * fills                 — per-execution rows, FK to proposals
--   * decisions             — debate audit trail (bull/bear/arbiter)
--   * equity_snapshots      — per-minute portfolio value snapshots

CREATE TABLE IF NOT EXISTS quanta_schema_version (
    version     INTEGER PRIMARY KEY,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reservations (
    client_order_id TEXT PRIMARY KEY,
    intent          JSONB NOT NULL,
    reserved_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS proposals (
    client_order_id TEXT PRIMARY KEY,
    venue           TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    side            TEXT NOT NULL CHECK (side IN ('BUY', 'SELL')),
    qty             NUMERIC(38, 18) NOT NULL CHECK (qty > 0),
    limit_price     NUMERIC(38, 18),
    strategy        TEXT NOT NULL,
    intent          JSONB NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS orders (
    client_order_id   TEXT PRIMARY KEY REFERENCES proposals(client_order_id) ON DELETE RESTRICT,
    exchange_order_id TEXT,
    status            TEXT NOT NULL CHECK (
        status IN ('PROPOSED', 'ACKED', 'PARTIAL', 'FILLED', 'CANCELLED', 'REJECTED')
    ),
    cancel_reason     TEXT,
    last_update       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fills (
    id              BIGSERIAL,
    client_order_id TEXT NOT NULL REFERENCES proposals(client_order_id) ON DELETE RESTRICT,
    venue_fill_id   TEXT,
    qty             NUMERIC(38, 18) NOT NULL CHECK (qty > 0),
    price           NUMERIC(38, 18) NOT NULL CHECK (price > 0),
    fee             NUMERIC(38, 18) NOT NULL DEFAULT 0,
    fee_currency    TEXT,
    side            TEXT NOT NULL CHECK (side IN ('BUY', 'SELL')),
    ts              TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (id, ts)
);

CREATE TABLE IF NOT EXISTS decisions (
    id        BIGSERIAL,
    ts        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    symbol    TEXT,
    strategy  TEXT,
    debate    JSONB NOT NULL,
    outcome   TEXT NOT NULL,
    rationale TEXT,
    PRIMARY KEY (id, ts)
);

CREATE TABLE IF NOT EXISTS equity_snapshots (
    ts           TIMESTAMPTZ NOT NULL,
    equity       NUMERIC(38, 18) NOT NULL,
    unrealized   NUMERIC(38, 18) NOT NULL DEFAULT 0,
    drawdown_pct NUMERIC(10, 6) NOT NULL DEFAULT 0,
    cash         NUMERIC(38, 18),
    PRIMARY KEY (ts)
);

CREATE INDEX IF NOT EXISTS idx_proposals_symbol_created
    ON proposals (symbol, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_proposals_strategy_created
    ON proposals (strategy, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status_last_update
    ON orders (status, last_update DESC);
CREATE INDEX IF NOT EXISTS idx_fills_client_order_id
    ON fills (client_order_id);
CREATE INDEX IF NOT EXISTS idx_fills_ts ON fills (ts DESC);
CREATE INDEX IF NOT EXISTS idx_decisions_ts ON decisions (ts DESC);
CREATE INDEX IF NOT EXISTS idx_decisions_symbol_ts
    ON decisions (symbol, ts DESC);
CREATE INDEX IF NOT EXISTS idx_equity_snapshots_ts
    ON equity_snapshots (ts DESC);
